### ISSUE TITLE
local replacement are not allowed when actually using pseudo-version

### ISSUE THREAD

**Issue by ylishev** [ldez/gomoddirectives#10]
If I have require in go.mod like this:
```
gitlab.our.com/go/ourpkg.git/ourmodule v0.1.1-0.20250428141953-3ec8962183c9
```
are you consider that to be a "local replacement"?

If you have a commit `3ec8962183c9` and place it as:
```
gitlab.our.com/go/ourpkg.git/ourmodule 3ec8962183c9
```
and run go mod tidy it will automatically replace the commit with that pseudo version:

https://go.dev/ref/mod#pseudo-versions

Just to emphasize that this commit is not necessary local and might be remotely pushed.

My current workaround is to add:

```yml
  settings:
    gomoddirectives:
      replace-local: true
```

but that feels like a bad "fix".

**Comment by ldez** [comment]
The pseudo versions are not local replacements: a local replacement is a replacement with a filesystem path.

This is based on https://github.com/golang/mod/blob/bc388b264a244501debfb9caea700c6dcaff10e2/module/module.go#L122-L124

> // Third, filesystem paths found in "replace" directives are
> // represented by a path with an empty version.

**Comment by ldez** [comment]
<details>
<summary>go.mod</summary>

```go
module github.com/golangci/sandbox

go 1.23.0

require github.com/ldez/gomoddirectives v0.6.1

require (
	github.com/ldez/grignotin v0.9.0 // indirect
	golang.org/x/mod v0.24.0 // indirect
	golang.org/x/tools v0.32.0 // indirect
)

replace github.com/ldez/gomoddirectives => github.com/ldez/gomoddirectives v0.6.2-0.20250414141443-ab57f6529c81
```

</details>

<details>
<summary>main.go</summary>

```go
package main

import (
	"fmt"

	_ "github.com/ldez/gomoddirectives"
)

func main() {
	fmt.Println("hello")
}

```

</details>


---

Default:

<details>
<summary>.golangci.yml</summary>

```yml
version: "2"

linters:
  default: none
  enable:
    - gomoddirectives
```

</details>

```console
$ golangci-lint run
go.mod:13:1: replacement are not allowed: github.com/ldez/gomoddirectives (gomoddirectives)
replace github.com/ldez/gomoddirectives => github.com/ldez/gomoddirectives v0.6.2-0.20250414141443-ab57f6529c81
^
1 issues:
* gomoddirectives: 1
```

---

`replace-local` has no effect.

<details>
<summary>.golangci.yml</summary>

```yml
version: "2"

linters:
  default: none
  enable:
    - gomoddirectives
  settings:
    gomoddirectives:
      replace-local: true

```

</details>

```console
$ golangci-lint run
go.mod:13:1: replacement are not allowed: github.com/ldez/gomoddirectives (gomoddirectives)
replace github.com/ldez/gomoddirectives => github.com/ldez/gomoddirectives v0.6.2-0.20250414141443-ab57f6529c81
^
1 issues:
* gomoddirectives: 1
```
