### ISSUE TITLE
Add details for "replacement are not allowed" case

### ISSUE THREAD

**Issue by sashamelentyev** [ldez/gomoddirectives#9]
Hello!
When I get "replacement are not allowed" issue, I don't understand why I can't replacement.
Please, add more details in issue

**Comment by ldez** [comment]
@sashamelentyev I'm not sure to understand.

Can you confirm my understanding?

You have a current project with `replace` directives, but some of them are allowed, and some others are not.
And you want to know the exact `replace` directive when the linter detects it.

Can you share your configuration, and maybe your `go.mod`?

**Comment by sashamelentyev** [comment]
You correct understand me.

I can't share go.mod, but replace looks like
```
require github.com/go-redis/redis/v8 v8.11.3

replace github.com/go-redis/redis/v8 => internal/mirrors/redis/go-redis/v8 v8.11.7
```

**Comment by ldez** [comment]
Can you share your configuration?

**Comment by sashamelentyev** [comment]
<details>

```
AR='ar'
CC='cc'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_ENABLED='1'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
CXX='c++'
GCCGO='gccgo'
GO111MODULE=''
GOARCH='arm64'
GOARM64='v8.0'
GOAUTH='netrc'
GOBIN=''
GOCACHE='/Users/sashamelentyev/Library/Caches/go-build'
GOCACHEPROG=''
GODEBUG=''
GOENV='/Users/sashamelentyev/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFIPS140='off'
GOFLAGS=''
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/k0/jqkzq6x14w516vk22qdc7qtc0000gn/T/go-build3105501612=/tmp/go-build -gno-record-gcc-switches -fno-common'
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMOD='go.mod'
GOMODCACHE='/Users/sashamelentyev/go/pkg/mod'
GONOPROXY='internal address'
GONOSUMDB='internal address'
GOOS='darwin'
GOPATH='/Users/sashamelentyev/go'
GOPRIVATE='internal address'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.24.1/libexec'
GOSUMDB='sum.golang.org'
GOTELEMETRY='on'
GOTELEMETRYDIR='/Users/sashamelentyev/Library/Application Support/go/telemetry'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.24.1/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.24.1'
GOWORK=''
PKG_CONFIG='pkg-config'
```

</details>

**Comment by ldez** [comment]
I'm asking for your current golangci-lint configuration, to understand how you configured the linter.

**Comment by sashamelentyev** [comment]
Sorry

<details>

```yaml
run:
  # The default concurrency value is the number of available CPU.
  concurrency: 4
  # Timeout for analysis, e.g. 30s, 5m.
  timeout: 5m
  # Include test files or not.
  tests: false
  # List of build tags, all linters use it.
  build-tags:
    - test
    - debug
  # If set we pass it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any changes
  # to go.mod are needed. This setting is most useful to check that go.mod does
  # not need updates, such as in a continuous integration and testing system.
  # If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores
  # the dependency descriptions in go.mod.
  #
  # Allowed values: readonly|vendor|mod
  # By default, it isn't set.
  modules-download-mode: readonly

  skip-dirs:
    - testgen
    - tools
    - unittest

  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: true
  # Define the Go version limit.
  # Mainly related to generics support since go1.18.
  go: '1.21'

output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  #
  # Multiple can be specified by separating them by comma, output can be provided
  # for each of them by separating format name and path by colon symbol.
  # Output path can be either `stdout`, `stderr` or path to the file to write to.
  # Example: "checkstyle:report.json,colored-line-number"
  formats:
    - format: colored-line-number
  # Print lines of code with issue.
  print-issued-lines: true
  # Print linter name in the end of issue text.
  print-linter-name: true
  # Make issues output unique by line.
  uniq-by-line: true
  # Sort results by: filepath, line and column.
  sort-results: true

linters-settings:
  gosimple:
    go: "1.21"
  goconst:
    numbers: true
  gomoddirectives:
    go-version-pattern: '^1\.23\.6$'

linters:
  fast: false

  presets:
    - bugs
    - comment
    - error
    - metalinter
    - performance
    - sql
    - unused
  enable:
    - gosimple
    - errname
    - goconst
    - nilnil
    - predeclared
    - tagliatelle
    - whitespace
    - gomoddirectives

  # Maximum issues count per one linter.
  # Set to 0 to disable.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  max-same-issues: 0
  # Fix found issues (if it's supported by the linter).
  fix: false
```

</details>

**Comment by ldez** [comment]
Your configuration is confusing me: the replace directives are not forbidden.

Can you create small example of a go.mod and what do you expect?

**Comment by sashamelentyev** [comment]
```
require github.com/go-redis/redis/v8 v8.11.3

replace github.com/go-redis/redis/v8 => internal/mirrors/redis/go-redis/v8 v8.11.7 // WITHOUT gomoddirectives issue HERE
```

**Comment by sashamelentyev** [comment]
Oh, I need add "internal/mirrors/redis/go-redis/v8" to replace-allow-list section? Or set replace-local as TRUE?

**Comment by ldez** [comment]
If you want to allow this replacement, yes you should  use `replace-allow-list`.


```yml
 gomoddirectives:
   replace-allow-list:
     - 'github.com/go-redis/redis/v8'
```
